export const jobRoles = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Web Designer",
  "UI Designer",
  "UX Designer",
  "DevOps Engineer",
  "Software Engineer",
  "Technical Support Engineer",
  "Project Manager",
  "Webmaster",
  "Copywriter",
  "Application Developer",
  "Frontend Engineer",
  "Web Application Developer",
  "Web Development Specialist",
  "Javascript Developer",
  "Dotnet Developer",
  "Web Development Manager",
  "Interface Engineer",
  "PHP Developer",
  "Programming Analyst",
  "User Experience Engineer",
  "Mobile App Developer",
  "Game Developer",
  "IoT & Hardware Developer",
  "Data Visualization & Analytics Engineer",
  "Web Security Engineer",
  "Frontend Architect / UI Engineer",
];

export const jobTypes = ["Full Time", "Part Time", "Internship"];
